name: GODABOT-CICD

on: push

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true # https://github.com/actions/checkout/issues/1471

      - name: Run tests
        run: make test

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        env:
          REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make image push

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true # https://github.com/actions/checkout/issues/1471

      - name: Set VERSION as env
        run: |
          echo "VERSION=$(git describe --abbrev=0 --tags)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Update image version in helm values
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.image.tag=strenv(VERSION)' helm/values.yaml

      - name: Commit changes in helm values
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update image version to $VERSION in helm values"
          git push
